name: Run CLI Commands and Write Output to File

on: 
  push:
    branches: [ repo-mode ]
  pull_request:
    branches: [ main ]

jobs:
  run-cli-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@v2

    - name: Install CLI App
      run: |
        brew tap PinedaVictor/vx
        brew install pinedavictor/vx/vexal

    - name: Run CLI Command and Capture Output
      run: |
        output=$(vx -v)
        echo "$output" > cli-output.txt

    # - name: Commit changes
    #   run: |
    #     git config --global user.name "github-actions[bot]"
    #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
    #     git add cli-output.txt
    #     git commit -m "Add output from CLI command"
    #     git push
